# Site settings
title: Beginnings with RPi
email: devin.carr0@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Documentation for Raspberry Pi information and installation.
baseurl: "/rpi" # the subpath of your site, e.g. /blog/
url: "https://devincarr.com" # the base hostname & protocol for your site
twitter_username: dev_in_space
github_username:  devincarr

# Build settings
markdown: kramdown

input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - LICENSE
  - README.md
